name: TarzaxNv
author: Tarzax
version: 1.0.0
api: 4.0.0
main: tarzax\nv\Main
website: https://github.com/TarzaxDev

commands:
  nv:
    usage: /nv
    description: "NightVison"
    permission: nv.use

permissions:
  nv.use:
    default: true
