# _______                       _   _       
#|__   __|                     | \ | |      
#  | | __ _ _ __ ______ ___  _|  \| |_   __
#  | |/ _` | '__|_  / _` \ \/ / . ` \ \ / /
#  | | (_| | |   / / (_| |>  <| |\  |\ V / 
#  |_|\__,_|_|  /___\__,_/_/\_\_| \_| \_/  
                                           
                                           

# TarzaxNv config
# v1.0.0
# permission is nv.use

NvOff: "ยง4- NightVision off -"
NvOn: "ยงa- NightVision on -"